ALTER TABLE INVENTAR DROP CONSTRAINT FK_INVENTAR_tipId
ALTER TABLE MOBILIER DROP CONSTRAINT FK_MOBILIER_OBIECTID
ALTER TABLE PERIFERICE DROP CONSTRAINT FK_PERIFERICE_OBIECTID
ALTER TABLE STATII DROP CONSTRAINT FK_STATII_calculatorId
ALTER TABLE CALCULATOR DROP CONSTRAINT FK_CALCULATOR_OBIECTID
ALTER TABLE FURNIZORIOFERTA DROP CONSTRAINT FK_FURNIZORIOFERTA_furnizorId
ALTER TABLE FURNIZORIOFERTA DROP CONSTRAINT FK_FURNIZORIOFERTA_obiectId
ALTER TABLE PERIFERICCASTI DROP CONSTRAINT FK_PERIFERICCASTI_OBIECTID
ALTER TABLE PERIFERICDISPLAY DROP CONSTRAINT FK_PERIFERICDISPLAY_OBIECTID
ALTER TABLE PERIFERICKEYBOARD DROP CONSTRAINT FK_PERIFERICKEYBOARD_OBIECTID
ALTER TABLE PERIFERICMOUSE DROP CONSTRAINT FK_PERIFERICMOUSE_OBIECTID
ALTER TABLE STOCINVANZARE DROP CONSTRAINT FK_STOCINVANZARE_obiectId
ALTER TABLE Statii_MOBILIERSTATIE DROP CONSTRAINT FK_Statii_MOBILIERSTATIE_Statii_STATIEID
ALTER TABLE Statii_PERIFERICESTATIE DROP CONSTRAINT FK_Statii_PERIFERICESTATIE_Statii_STATIEID
DROP TABLE FURNIZORI CASCADE
DROP TABLE INVENTAR CASCADE
DROP TABLE MOBILIER CASCADE
DROP TABLE PERIFERICE CASCADE
DROP TABLE STATII CASCADE
DROP TABLE CALCULATOR CASCADE
DROP TABLE FURNIZORIOFERTA CASCADE
DROP TABLE PERIFERICCASTI CASCADE
DROP TABLE PERIFERICDISPLAY CASCADE
DROP TABLE PERIFERICKEYBOARD CASCADE
DROP TABLE PERIFERICMOUSE CASCADE
DROP TABLE SALACALCULATOARE CASCADE
DROP TABLE STOCINVANZARE CASCADE
DROP TABLE TIPINVENTAR CASCADE
DROP TABLE Statii_MOBILIERSTATIE CASCADE
DROP TABLE Statii_PERIFERICESTATIE CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
